running tests now uses builtin libwasmer

diff --git a/bin/test b/bin/test
--- a/bin/test
+++ b/bin/test
@@ -22,18 +22,18 @@ for test_file in $(find tests/ -name '*.onyx'); do
 
     print_check "$name"
 
-    if command -v wasmer >/dev/null; then
-        if ! ./bin/onyx --use-post-mvp-features "$test_file" -o "./tests/$name.wasm" >/dev/null; then
+    if true; then
+        if ! ./bin/onyx run "$test_file" > ./tmpoutput; then
             printf "\n❌ Failed to compile $name.onyx.\n"
             failed=1
             continue
         fi
         
-        if ! wasmer "./tests/$name.wasm" > ./tmpoutput; then
-            printf "\n❌ Failed to run $name.onyx.\n"
-            failed=1
-            continue
-        fi
+        # if ! wasmer "./tests/$name.wasm" > ./tmpoutput; then
+        #     printf "\n❌ Failed to run $name.onyx.\n"
+        #     failed=1
+        #     continue
+        # fi
     else
         if ! ./bin/onyx -r js --use-post-mvp-features "$test_file" -o "./tests/$name.wasm" >/dev/null; then
             printf "\n❌ Failed to compile $name.onyx.\n"
@@ -57,7 +57,7 @@ for test_file in $(find tests/ -name '*.onyx'); do
 
     echo "✔ Passed"
 
-    rm "./tests/$name.wasm"
+    rm "./tests/$name.wasm" 2>/dev/null
 done
 rm ./tmpoutput
 
